### PR TITLE
feat: add typing

### PR DESCRIPTION
**Pull request by xiaoxiangmoe**

### CODE REVIEW

**Comment by xiaoxiangmoe** [comment]
@feross can you review it?

**Comment by xiaoxiangmoe** [comment]
@feross can you review it?

**Comment by xiaoxiangmoe** [comment]
@feross Should I publish it to DefinitelyTyped?

**Comment by xiaoxiangmoe** [comment]
@feross Any update？

**Comment by xiaoxiangmoe** [comment]
@feross What is the status of this library?

**Review by feross — APPROVED** [review]

**Comment by feross** [comment]
Released as 2.2.0

**Pull request merged**
